import {useEffect,useState,useRef,type ReactNode} from 'react';
import {FileText,ArrowUpRight} from 'lucide-react';
import type {SituationContext} from '../../services/situations';
import type {ContextualActor} from '../../services/contextualActors';
import {dossierDetails} from '../../services/dossierDetails';
import {situationDocuments,type SituationDocumentsClient,type DocumentAvailability} from '../../services/situationDocuments';
const origins:Record<string,string>={'operator-created':'Created by operator',received:'Received document',local:'Local project file · authorship not recorded',generated:'Generated / supplied summary',referenced:'Referenced in source'};
export function DossierTabs({context,workstream,actor,situationId,children,provenance,documentContext,documentsApi=situationDocuments}:{context:SituationContext;workstream:string;actor?:ContextualActor;situationId?:string;children:ReactNode;provenance?:ReactNode;documentContext?:ReactNode;documentsApi?:SituationDocumentsClient}){
 const [tab,setTab]=useState('Overview'),[files,setFiles]=useState<DocumentAvailability[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const details=dossierDetails(context,workstream,actor);
 const root=useRef<HTMLDivElement>(null),sourceStamp=context.sources.map(s=>s.id+':'+s.path).join('|');
 useEffect(()=>{const panel=root.current?.closest('.contextual-inspector');if(panel)panel.scrollTop=0},[tab]);
 useEffect(()=>{if(tab==='Timeline'&&!details.timeline.length)setTab('Overview')},[tab,details.timeline.length]);
 useEffect(()=>{let active=true;setFiles([]);setError('');if(situationId){setLoading(true);documentsApi.status(situationId).then(next=>{if(active)setFiles(next)}).catch(()=>{if(active)setError('File availability could not be checked.')}).finally(()=>{if(active)setLoading(false)})}return()=>{active=false}},[situationId,sourceStamp,documentsApi,tab==='Documents']);
 const tabs=['Overview','Documents','Related',...(details.timeline.length?['Timeline']:[])];
 function choose(next:string){setTab(next);setError('')}
 function documentRows(limit?:number){return details.documents.slice(0,limit).map(doc=>{const state=files.find(f=>f.id===doc.id);return <article className="dossier-document" key={doc.id}><FileText size={17}/><div><strong>{doc.title}</strong><small>{doc.type} · {doc.document?.date??'Date not recorded'}</small><small>{origins[doc.origin]}{doc.document?.from?` · ${doc.document.from}`:''}</small>{doc.document?.description&&<p>{doc.document.description}</p>}<small>{state?.available?'Local file available':loading?'Checking local file…':state||!doc.path||doc.origin==='referenced'?'Referenced, file not currently available':'Local availability not checked'}</small>{state?.available&&!state.openable&&<small>Opening this file type is not supported.</small>}</div>{state?.available&&state.openable&&situationId&&<button aria-label={`Open document: ${doc.title}`} onClick={()=>void documentsApi.open(situationId,doc.id).catch(()=>setError('The file could not be opened. It may have moved or become unavailable.'))}>Open <ArrowUpRight size={12}/></button>}{tab==='Documents'&&<details><summary>Source details</summary><p>{doc.category}</p><code>{doc.path||'No local path recorded'}</code><small>Source ID: {doc.id}</small></details>}</article>})}
 return <div ref={root} className="dossier-detail-body"><nav className="dossier-tabs" role="tablist" aria-label="Dossier views">{tabs.map(name=><button key={name} role="tab" aria-selected={tab===name} tabIndex={tab===name?0:-1} onKeyDown={e=>{let index=tabs.indexOf(name);if(e.key==='ArrowRight')index=(index+1)%tabs.length;else if(e.key==='ArrowLeft')index=(index+tabs.length-1)%tabs.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else return;e.preventDefault();choose(tabs[index]);(e.currentTarget.parentElement?.children[index] as HTMLElement)?.focus()}} aria-controls="dossier-tab-panel" onClick={()=>choose(name)}>{name}</button>)}</nav>{error&&<p role="alert">{error}</p>}<div id="dossier-tab-panel" role="tabpanel" aria-label={tab}>
 {tab==='Overview'&&<>{children}<section className="dossier-supporting"><h5>Supporting documents</h5>{details.documents.length?documentRows(2):<p>No documents linked to this scope.</p>}{details.documents.length>0&&<button className="dossier-text-link" onClick={()=>choose('Documents')}>View documents ({details.documents.length})</button>}</section>{details.related.length>0&&<section><h5>Related people &amp; companies</h5>{details.related.slice(0,2).map((r,i)=><p key={i}>{r.people.filter(p=>p.name!==actor?.primary).map(p=>p.name).join(' · ')} <small>· {r.certainty}</small></p>)}<button className="dossier-text-link" onClick={()=>choose('Related')}>View relationships ({details.related.length})</button></section>}{!details.timeline.length&&<small className="dossier-empty-timeline">No dated milestones recorded for this scope.</small>}{provenance&&<details className="dossier-provenance"><summary>Source details</summary>{provenance}</details>}</>}
 {tab==='Documents'&&<><h5>Documents · {details.documents.length}</h5><p className="dossier-scope-note">Linked source files. Shared documents do not establish authorship or exclusive ownership.</p>{details.documents.length?documentRows():<p>No documents linked to this scope.</p>}{documentContext&&<details><summary>Supporting context &amp; qualifications</summary>{documentContext}</details>}</>}
 {tab==='Related'&&<><h5>People &amp; companies</h5>{details.related.length?details.related.map((r,i)=><article className="dossier-related" key={i}>{r.people.map(p=><div key={p.id}><strong>{p.name}</strong><small>{p.role}</small></div>)}<p>{r.description}</p><small>{r.certainty}</small></article>):<p>No additional relationships are recorded for this scope.</p>}</>}
 {tab==='Timeline'&&<><h5>Relationship timeline</h5><ol className="dossier-timeline">{details.timeline.map(event=><li key={event.id}><time>{event.date}</time><span data-event-state={event.state}>{event.state}</span><strong>{event.title}</strong><details><summary>Sources</summary>{event.refs.map((r,i)=><p key={i}>{context.sources.find(s=>s.id===r.sourceId)?.title??r.sourceId} · {r.locator}</p>)}</details></li>)}</ol></>}
 </div></div>;
}
