import {mapName,mapAnchorLabel} from '../../services/mapTypography';
import {useEffect,useLayoutEffect,useRef,useState,type CSSProperties} from 'react';
import {edgeBoundary,layoutSituationGraph,layoutSituationOverview,situationGraphBounds,mapDensity,mapFitScale,MAP_ZOOM_LEVELS,MAP_NAME_COLUMNS,type GraphGroup} from '../../services/situationGraph';
import {Home,Network,ArrowUpRight,Landmark,Wrench,Shield,Plug,KeyRound,Users,Plus,Minus,Scan} from 'lucide-react';
import type {SituationContext} from '../../services/situations';

/**
 * The relationship map. Node geometry lives in graph units; the rendered scale
 * comes from the measured canvas, capped at 1.1× so wide screens do not
 * inflate cards. Text never follows the scale below its floor (review U8,
 * D1): CSS sizes it with max(base, floor / --map-scale), and the density
 * attribute drops secondary lines so the larger text still fits. Every node
 * stays on the page; full names remain in titles and accessible labels.
 */
export function SituationRelationshipWeb({title,groups,relationships=[],selected,onSelect,onGroup,personOnly=[]}:{title:string;groups:GraphGroup[];relationships?:SituationContext['relationships'];selected:string;onSelect:(id:string)=>void;onGroup?:(id:string)=>void;personOnly?:string[]}){
 const graph=onGroup?layoutSituationOverview(title,groups):layoutSituationGraph(title,groups,relationships),[level,setLevel]=useState(0),[hovered,setHovered]=useState('');
 const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 const canvas=useRef<HTMLDivElement>(null),previousZoom=useRef(1),zoom=MAP_ZOOM_LEVELS[level],bounds=situationGraphBounds(graph.nodes);
 const [frame,setFrame]=useState<{width:number;height:number}|null>(null);
 const empty=!onGroup&&!groups.some(g=>g.actors.length);
 useLayoutEffect(()=>{const el=canvas.current;if(!el)return;const measure=()=>{const width=el.clientWidth,height=el.clientHeight;if(width>0&&height>0)setFrame(f=>f&&f.width===width&&f.height===height?f:{width,height})};measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect()},[empty]);
 useLayoutEffect(()=>{const el=canvas.current;if(!el)return;if(level===0){el.scrollLeft=0;el.scrollTop=0}else{const ratio=zoom/previousZoom.current;el.scrollLeft=(el.scrollLeft+el.clientWidth/2)*ratio-el.clientWidth/2;el.scrollTop=(el.scrollTop+el.clientHeight/2)*ratio-el.clientHeight/2}previousZoom.current=zoom},[level,zoom]);
 const reset=()=>{setLevel(0);if(canvas.current){canvas.current.scrollLeft=0;canvas.current.scrollTop=0}};
 const iconFor=(label:string)=>/renovat|repair|inspect|roof|electric/i.test(label)?Wrench:/mortgage|financ/i.test(label)?Landmark:/insur/i.test(label)?Shield:/utilit|water/i.test(label)?Plug:/closing/i.test(label)?KeyRound:/HOA|community/i.test(label)?Users:Network;
 const fit=frame?mapFitScale(frame,bounds):null,scale=fit===null?null:fit*zoom,density=mapDensity(scale),columns=MAP_NAME_COLUMNS[density];
 const svgSize:CSSProperties=scale===null?{width:`${zoom*100}%`,height:`${zoom*100}%`}:{width:`${Math.floor(bounds.width*scale)}px`,height:`${Math.floor(bounds.height*scale)}px`};
 const recommendedNode=onGroup?'group:'+groups.find(g=>g.priority?.recommended)?.id:'';
 const byId=new Map(graph.nodes.map(n=>[n.id,n]));
 const shownPersonOnly=graph.nodes.filter(n=>n.actor&&personOnly.includes(n.id)).length,actorCount=graph.nodes.filter(n=>n.actor).length;
 const zoomIn=()=>setLevel(l=>Math.min(MAP_ZOOM_LEVELS.length-1,l+1)),zoomOut=()=>setLevel(l=>Math.max(0,l-1));
 // A scope with no supported actors is a sentence, not a lone anchor scaled up to fill the canvas.
 if(empty)return <div className="relationship-stage relationship-empty" data-zoom-level={0}><div className="graph-empty-state" role="status"><strong>{title}</strong><p>No supported actors are recorded in this scope.</p><small>Saved context and correspondence name no people or companies here yet.</small></div></div>;
 return <div className="relationship-stage" data-zoom-level={level} data-density={density} style={{'--map-scale':scale??1} as CSSProperties}><div ref={canvas} className="relationship-viewport" tabIndex={0} aria-label="Relationship map canvas. Press plus or minus to zoom" aria-keyshortcuts="+ -" onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='+'||e.key==='='){e.preventDefault();e.stopPropagation();zoomIn()}else if(e.key==='-'){e.preventDefault();e.stopPropagation();zoomOut()}}}><svg className="relationship-web" role="group" aria-label={`${title} relationship web`} viewBox={`${bounds.x} ${bounds.y} ${bounds.width} ${bounds.height}`} style={svgSize}>

 <g className="graph-edges">{graph.edges.map((edge,i)=>{const a=byId.get(edge.from)!,b=byId.get(edge.to)!,start=edgeBoundary(a,b),end=edgeBoundary(b,a);const path=`M${start.x},${start.y} C${start.x+(end.x-start.x)*.55},${start.y} ${end.x-(end.x-start.x)*.55},${end.y} ${end.x},${end.y}`;return <g key={edge.from+edge.to+i}><path data-from={edge.from} data-to={edge.to} className={`graph-edge ${edge.kind} ${edge.uncertain?'uncertain':''} ${edge.from===recommendedNode||edge.to===recommendedNode?'priority-edge':''} ${[hovered,selected].some(id=>id&&(id===edge.from||id===edge.to))?'highlighted':''}`} d={path}><title>{edge.description}{edge.refs?.length?` · ${edge.refs.length} evidence ${edge.refs.length===1?'reference':'references'}`:''}</title></path><circle className="graph-track-port" cx={end.x} cy={end.y} r="3"/>{!reduced&&edge.kind==='structure'&&<g className="graph-travel-light" aria-hidden="true"><circle r="6" className="graph-light-halo"/><circle r="1.8" className="graph-light-core"/><animateMotion path={path} dur="4.5s" begin={`${-(i*.63)%4.5}s`} repeatCount="indefinite" keyPoints="0;1;1" keyTimes="0;0.444;1" calcMode="linear"/><animate attributeName="opacity" values="0;1;1;0;0" keyTimes="0;0.06;0.38;0.444;1" dur="4.5s" begin={`${-(i*.63)%4.5}s`} repeatCount="indefinite"/></g>}</g>})}</g>
 {graph.nodes.map(n=><foreignObject key={n.id} className={`graph-node graph-${n.kind}`} data-node-id={n.id} onMouseEnter={()=>setHovered(n.id)} onMouseLeave={()=>setHovered('')} onFocus={()=>setHovered(n.id)} onBlur={()=>setHovered('')} x={n.x-n.width/2} y={n.y-n.height/2} width={n.width} height={n.height}>{n.actor?<button title={[n.actor.primary,...n.actor.representatives,n.actor.role,personOnly.includes(n.id)?'Organization unconfirmed':''].filter(Boolean).join(' · ')} className={`contextual-actor situation-person ${n.actor.state} ${personOnly.includes(n.id)?'org-unconfirmed':''}`} aria-label={`View ${n.actor.primary}${graph.nodes.filter(node=>node.actor?.primary===n.actor?.primary).length>1?' · '+n.actor.role:''}`} aria-pressed={selected===n.id} onClick={()=>onSelect(n.id)}><strong>{mapName(n.actor.primary,columns)}</strong>{!!n.actor.representatives.length&&<span>{n.actor.representatives.join(' · ')}</span>}<em>{n.actor.role}</em>{personOnly.includes(n.id)?<small className="sr-only">Organization unconfirmed</small>:n.actor.state!=='documented'&&<small>{n.actor.state==='reported'?'Reported':'Unconfirmed'}</small>}</button>:n.kind==='anchor'?<div className="graph-anchor-content" title={title}>{onGroup&&/^home$/i.test(title)?<Home size={34}/>:<Network size={30}/>}<strong>{mapAnchorLabel(title,density==='full'?14:density==='compact'?12:11)}</strong><span aria-hidden="true">Ω</span></div>:<button className={`graph-hub ${onGroup?'graph-workstream-card':''}`} aria-description={onGroup?groups.find(g=>g.id===n.groupId)?.priority?.reason:undefined} data-priority={onGroup?groups.find(g=>g.id===n.groupId)?.priority?.level:undefined} data-recommended={onGroup&&groups.find(g=>g.id===n.groupId)?.priority?.recommended||undefined} title={[n.label,onGroup?groups.find(g=>g.id===n.groupId)?.priority?.reason:undefined].filter(Boolean).join(' · ')} aria-label={`Explore ${n.label}`} onClick={()=>onGroup?.(n.groupId!)} disabled={!onGroup}>{onGroup&&(()=>{const Icon=iconFor(n.label);return <Icon size={23}/>})()}<span>{n.label}</span>{onGroup&&['needs-attention','review-soon'].includes(groups.find(g=>g.id===n.groupId)?.priority?.level??'')&&<i className="graph-priority-mark" aria-hidden="true"/>}{onGroup&&<ArrowUpRight className="graph-explore-arrow" size={15}/ >}{onGroup&&<div className="graph-workstream-preview">{groups.find(g=>g.id===n.groupId)?.actors.filter((a,i,list)=>list.findIndex(b=>b.primary===a.primary)===i).slice(0,2).map(a=><div key={a.id} title={a.primary}>{mapName(a.primary,columns)}</div>)}{(n.total??0)>2&&<small>+ {(n.total??0)-2} more</small>}</div>}<small>{n.total} {n.total===1?'actor':'actors'}</small></button>}</foreignObject>)}
 </svg></div><small className="map-zoom-hint" aria-hidden="true">Press + or − to zoom</small><div className="relationship-graph-controls" aria-label="Map navigation"><button aria-label="Zoom out" title="Zoom out (−)" disabled={level===0} onClick={zoomOut}><Minus size={16}/></button><button aria-label="Reset view" title="Reset view" onClick={reset}><Scan size={16}/></button><button aria-label="Zoom in" title="Zoom in (+)" disabled={level===MAP_ZOOM_LEVELS.length-1} onClick={zoomIn}><Plus size={16}/></button></div>{shownPersonOnly>0&&<small className="graph-legend"><span className="graph-legend-mark" aria-hidden="true">○</span> {shownPersonOnly===actorCount?`Organization unconfirmed for ${actorCount===1?'this contact':`all ${actorCount} contacts`}.`:'Organization unconfirmed.'}</small>}</div>;
}
