import {mapName} from '../../services/mapTypography';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {edgeBoundary,layoutSituationGraph,layoutSituationOverview,situationGraphBounds,MAP_ZOOM_LEVELS,type GraphGroup} from '../../services/situationGraph';
import {Home,Network,ArrowUpRight,Landmark,Wrench,Shield,Plug,KeyRound,Users,Plus,Minus,Scan} from 'lucide-react';
import type {SituationContext} from '../../services/situations';
export function SituationRelationshipWeb({title,groups,relationships=[],selected,onSelect,onGroup,personOnly=[]}:{title:string;groups:GraphGroup[];relationships?:SituationContext['relationships'];selected:string;onSelect:(id:string)=>void;onGroup?:(id:string)=>void;personOnly?:string[]}){
 const graph=onGroup?layoutSituationOverview(title,groups):layoutSituationGraph(title,groups,relationships),[level,setLevel]=useState(0),[hovered,setHovered]=useState('');
 const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 const canvas=useRef<HTMLDivElement>(null),previousZoom=useRef(1),zoom=MAP_ZOOM_LEVELS[level],bounds=situationGraphBounds(graph.nodes);
 useLayoutEffect(()=>{const el=canvas.current;if(!el)return;if(level===0){el.scrollLeft=0;el.scrollTop=0}else{const ratio=zoom/previousZoom.current;el.scrollLeft=(el.scrollLeft+el.clientWidth/2)*ratio-el.clientWidth/2;el.scrollTop=(el.scrollTop+el.clientHeight/2)*ratio-el.clientHeight/2}previousZoom.current=zoom},[level,zoom]);
 const reset=()=>{setLevel(0);if(canvas.current){canvas.current.scrollLeft=0;canvas.current.scrollTop=0}};
 const iconFor=(label:string)=>/renovat|repair|inspect|roof|electric/i.test(label)?Wrench:/mortgage|financ/i.test(label)?Landmark:/insur/i.test(label)?Shield:/utilit|water/i.test(label)?Plug:/closing/i.test(label)?KeyRound:/HOA|community/i.test(label)?Users:Network;

 const recommendedNode=onGroup?'group:'+groups.find(g=>g.priority?.recommended)?.id:'';
 const byId=new Map(graph.nodes.map(n=>[n.id,n]));
 return <div className="relationship-stage" data-zoom-level={level}><div ref={canvas} className="relationship-viewport" tabIndex={0} aria-label="Relationship map canvas" onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='+'||e.key==='='){e.preventDefault();e.stopPropagation();setLevel(l=>Math.min(MAP_ZOOM_LEVELS.length-1,l+1))}else if(e.key==='-'){e.preventDefault();e.stopPropagation();setLevel(l=>Math.max(0,l-1))}}}><svg className="relationship-web" role="group" aria-label={`${title} relationship web`} viewBox={`${bounds.x} ${bounds.y} ${bounds.width} ${bounds.height}`} style={{width:`${zoom*100}%`,height:`${zoom*100}%`}}>

 <g className="graph-edges">{graph.edges.map((edge,i)=>{const a=byId.get(edge.from)!,b=byId.get(edge.to)!,start=edgeBoundary(a,b),end=edgeBoundary(b,a);const path=`M${start.x},${start.y} C${start.x+(end.x-start.x)*.55},${start.y} ${end.x-(end.x-start.x)*.55},${end.y} ${end.x},${end.y}`;return <g key={edge.from+edge.to+i}><path data-from={edge.from} data-to={edge.to} className={`graph-edge ${edge.kind} ${edge.uncertain?'uncertain':''} ${edge.from===recommendedNode||edge.to===recommendedNode?'priority-edge':''} ${[hovered,selected].some(id=>id&&(id===edge.from||id===edge.to))?'highlighted':''}`} d={path}><title>{edge.description}{edge.refs?.length?` · ${edge.refs.length} evidence references`:''}</title></path><circle className="graph-track-port" cx={end.x} cy={end.y} r="3"/>{!reduced&&edge.kind==='structure'&&<g className="graph-travel-light" aria-hidden="true"><circle r="6" className="graph-light-halo"/><circle r="1.8" className="graph-light-core"/><animateMotion path={path} dur="4.5s" begin={`${-(i*.63)%4.5}s`} repeatCount="indefinite" keyPoints="0;1;1" keyTimes="0;0.444;1" calcMode="linear"/><animate attributeName="opacity" values="0;1;1;0;0" keyTimes="0;0.06;0.38;0.444;1" dur="4.5s" begin={`${-(i*.63)%4.5}s`} repeatCount="indefinite"/></g>}</g>})}</g>
 {graph.nodes.map(n=><foreignObject key={n.id} className={`graph-node graph-${n.kind}`} data-node-id={n.id} onMouseEnter={()=>setHovered(n.id)} onMouseLeave={()=>setHovered('')} onFocus={()=>setHovered(n.id)} onBlur={()=>setHovered('')} x={n.x-n.width/2} y={n.y-n.height/2} width={n.width} height={n.height}>{n.actor?<button title={[n.actor.primary,...n.actor.representatives,n.actor.role].join(' · ')} className={`contextual-actor situation-person ${n.actor.state}`} aria-label={`View ${n.actor.primary}${graph.nodes.filter(node=>node.actor?.primary===n.actor?.primary).length>1?' · '+n.actor.role:''}`} aria-pressed={selected===n.id} onClick={()=>onSelect(n.id)}><strong>{mapName(n.actor.primary)}</strong>{!!n.actor.representatives.length&&<span>{n.actor.representatives.join(' · ')}</span>}<em>{n.actor.role}</em>{personOnly.includes(n.id)?<small>Organization unconfirmed</small>:n.actor.state!=='documented'&&<small>{n.actor.state==='reported'?'Reported':'Unconfirmed'}</small>}</button>:n.kind==='anchor'?<div className="graph-anchor-content">{onGroup&&/^home$/i.test(title)?<Home size={34}/>:<Network size={30}/>}<strong>{title}</strong><span>Ω</span></div>:<button className={`graph-hub ${onGroup?'graph-workstream-card':''}`} aria-description={onGroup?groups.find(g=>g.id===n.groupId)?.priority?.reason:undefined} data-priority={onGroup?groups.find(g=>g.id===n.groupId)?.priority?.level:undefined} data-recommended={onGroup&&groups.find(g=>g.id===n.groupId)?.priority?.recommended||undefined} title={[n.label,onGroup?groups.find(g=>g.id===n.groupId)?.priority?.reason:undefined].filter(Boolean).join(' · ')} aria-label={`Explore ${n.label}`} onClick={()=>onGroup?.(n.groupId!)} disabled={!onGroup}>{onGroup&&(()=>{const Icon=iconFor(n.label);return <Icon size={23}/>})()}<span>{n.label}</span>{onGroup&&['needs-attention','review-soon'].includes(groups.find(g=>g.id===n.groupId)?.priority?.level??'')&&<i className="graph-priority-mark" aria-hidden="true"/>}{onGroup&&<ArrowUpRight className="graph-explore-arrow" size={15}/ >}{onGroup&&<div className="graph-workstream-preview">{groups.find(g=>g.id===n.groupId)?.actors.filter((a,i,list)=>list.findIndex(b=>b.primary===a.primary)===i).slice(0,2).map(a=><div key={a.id} title={a.primary}>{mapName(a.primary)}</div>)}{(n.total??0)>2&&<small>+ {(n.total??0)-2} more</small>}</div>}<small>{n.total} {n.total===1?'actor':'actors'}</small></button>}</foreignObject>)}
 </svg></div><div className="relationship-graph-controls" aria-label="Map navigation"><button aria-label="Zoom out" title="Zoom out (−)" disabled={level===0} onClick={()=>setLevel(l=>Math.max(0,l-1))}><Minus size={16}/></button><button aria-label="Reset view" title="Reset view" onClick={reset}><Scan size={16}/></button><button aria-label="Zoom in" title="Zoom in (+)" disabled={level===MAP_ZOOM_LEVELS.length-1} onClick={()=>setLevel(l=>Math.min(MAP_ZOOM_LEVELS.length-1,l+1))}><Plus size={16}/></button></div>{!groups.some(g=>g.actors.length)&&<small className="graph-empty-note">No supported actors recorded in this scope.</small>}</div>;
}
