import {superpowers} from '../../services/skillCollections';
import './skillCollection.css';
export function SkillCollection({connected=false}:{connected?:boolean}){
 return <section className="skill-collection" aria-label="Superpowers collection">
  <header><div><span className="command-eyebrow">SKILL COLLECTION</span><h3>Superpowers</h3></div><span className="armory-state">Reference available</span></header>
  <p>A development workflow for planning, debugging, testing and reviewing substantial engineering work.</p>
  <ol className="collection-chain" aria-label="Knowledge lineage"><li>Source</li><li>Olympus summary</li><li>Agent loadout</li><li>Mission evidence</li><li>Memory</li></ol>
  <dl className="collection-facts"><div><dt>Source</dt><dd><a href={`${superpowers.repository}/tree/${superpowers.revision}`} target="_blank" rel="noreferrer">obra/superpowers · {superpowers.revision.slice(0,7)}</a><small>Reviewed {superpowers.reviewed} · MIT</small></dd></div><div><dt>Olympus</dt><dd>Curated reference · execution not connected</dd></div><div><dt>Codex</dt><dd>Managed separately in Codex Plugins. Installation status is not observed by Olympus.</dd></div><div><dt>Agent relationship</dt><dd>Suggested for Hephaestus · not assigned</dd></div><div><dt>Mission evidence</dt><dd>{connected ? "Exact guidance preparation is recorded in delegation history. Delivery is not proof of compliance; inspect the results." : "Usage tracking is not connected for this collection."}</dd></div></dl>
  <h4>Curated skills</h4><p className="armory-muted">Six starting points from the upstream collection. Expand a skill to inspect its purpose and pinned source.</p>
  <div className="collection-skills">{superpowers.skills.map(([id,name,summary])=><details key={id}><summary>{name}</summary><p>{summary}</p><a href={`${superpowers.repository}/blob/${superpowers.revision}/skills/${id}/SKILL.md`} target="_blank" rel="noreferrer">Read source instructions</a></details>)}</div>
  <h4>Olympus application rules</h4><ul><li>Use a lightweight process for cosmetic edits; reserve full planning for substantial work.</li><li>Preserve Olympus memory, source provenance and existing execution boundaries.</li><li>Every Monid execution and spend requires a separate, scoped approval.</li><li>Inspection does not assign a skill, start a mission or grant tool access.</li></ul>
  <p className="armory-footnote">This is an Olympus-authored digestion of the pinned source, not an imported executable skill pack. {connected ? "The reviewed adaptation is supplied through separately approved planning and implementation launches. Automatic memory links remain unconnected." : "The lineage above describes the intended connection; assignments, mission history and automatic memory links are not yet connected."}</p>
 </section>;
}
