import { invoke, isTauri } from "@tauri-apps/api/core";
export interface MailExcerpt { provider:string; accountId:string; messageId:string; threadId:string; sender:string; subject:string; timestamp:number; excerpt:string; fingerprint:string; retrievedAt:string; bodyStatus:string; cachedThreadSubset:boolean }
export interface MailMessage { id:string; threadId:string; sender:string; recipients:string; subject:string; internalDate:number; canonicalText:string; cleanText:string; bodyStatus:string; attachments:{filename:string;mimeType:string;size:number}[] }
export interface GmailStatus { configured:boolean; configPath:string; busy:boolean; cachedMessages:number; account:null|{id:string;email:string;enabled:boolean;status:string;horizonDays:number;lastSuccess:string|null;lastAttempt:string|null;lastError:string|null;nextSync:string|null}; lastRun:null|{status:string;mode:string;changes:number;error:string|null}; candidates:{kind:string;text:string;messageId:string;threadId:string;accountId:string;fingerprint:string;sender:string;subject:string;timestamp:number}[] }
export const gmailNative = isTauri;
export const gmailStatus=()=>invoke<GmailStatus>("gmail_status");
export const gmailAction=(action:"connect"|"disconnect"|"sync"|"cancel")=>invoke<void>(`gmail_${action}`);
export const gmailHorizon=(days:number)=>invoke<void>("gmail_set_horizon",{days});
export const gmailSearch=(query:string)=>invoke<MailExcerpt[]>("gmail_search",{query});
export const gmailThread=(threadId:string)=>invoke<MailMessage[]>("gmail_thread",{threadId});
export function gmailStateLabel(state:GmailStatus|null):string {if(!state)return "Loading connection…";if(state.busy)return state.account?.status==="syncing"?"Synchronizing…":"Connection operation in progress…";if(!state.account?.enabled)return "Not connected";return ({connected:"Connected · read only",sync_error:"Sync error",authentication_required:"Authentication required",syncing:"Synchronizing…"} as Record<string,string>)[state.account.status]??"Connection needs review";}
export function gmailError(code:unknown):string {const key=String(code);const known:Record<string,string>={gmail_api_disabled:"Enable Gmail API in the Google Cloud project that owns this Desktop OAuth client, then retry.",gmail_scope_insufficient:"Google reports insufficient permission. Reconnect and grant the requested read-only Gmail permission.",gmail_quota_exceeded:"Google reports an exhausted API quota. Check this project’s Gmail API quota and retry after it resets.",gmail_domain_policy:"Your Google Workspace administrator blocks this application’s Gmail access.",gmail_client_config_missing:"Save your Desktop OAuth client file at the path shown below.",gmail_requires_desktop_client:"This configuration must be a Google Desktop app OAuth client.",oauth_cancelled:"Authorization cancelled. Existing connection settings were preserved.",oauth_state_mismatch:"Authorization response could not be verified. Please connect again.",oauth_callback_timeout:"Authorization timed out. Choose Connect to try again.",gmail_authentication_required:"Google authorization has expired or was revoked. Reconnect Gmail.",gmail_credential_missing:"The Windows credential is missing. Reconnect Gmail.",gmail_secure_store_unavailable:"Windows Credential Manager could not be accessed. If disconnecting, sync is stopped but credential removal must be retried.",gmail_network_unavailable:"Network unavailable. The previous cache and cursor are preserved.",gmail_scope_limit_reduce_horizon:"This sync exceeds the 2,000-message safety limit. Choose a smaller date range and sync again.",gmail_rate_limited:"Google rate-limited this sync. Olympus will retry on its next cadence.",gmail_access_or_quota_denied:"Google denied access or quota. Check Gmail API enablement and consent, then retry.",gmail_operation_running:"Another Gmail operation is still running.",gmail_disconnect_before_switching_account:"Disconnect the current account before connecting a different account.",gmail_cancelled:"Sync cancelled. The previous committed cache is preserved."};return known[key]??`Gmail could not complete this operation (${key.replace(/[^a-zA-Z0-9_]/g, "").slice(0,90)}). Retry or check the setup guide.`;}

export const gmailRemoveCache=()=>invoke<void>("gmail_remove_cache",{confirmed:true});
