import {RealtimeVoice, type VoiceDependencies} from "./realtimeVoice";
import {conversationTurnContent} from "./assistant";
import {voiceDepthFor,validateVoiceNavigation} from "./voiceContract";
import type {VoiceAnswer, VoiceMessageMetadata} from "./voiceContract";
export async function runRealtimeVoiceHarness(){
 let passed=0;const check=(condition:unknown,label:string)=>{if(!condition)throw Error(label);passed++;};
 const wait=()=>new Promise(resolve=>setTimeout(resolve,0));
 let stopped=0, paused=0;const sent:Record<string,any>[]=[];
 const track={stop:()=>stopped++,onended:null};
 const stream={getTracks:()=>[track]} as unknown as MediaStream;
 const audio={autoplay:false,muted:true,srcObject:null,pause:()=>paused++,play:async()=>{},onerror:null} as unknown as HTMLAudioElement;
 const dc={readyState:"open",onmessage:null,onopen:null,onclose:null,send:(value:string)=>sent.push(JSON.parse(value)),close:()=>{}} as unknown as RTCDataChannel;
 const pc={addTrack:()=>{},createDataChannel:()=>dc,createOffer:async()=>({sdp:"offer"}),setLocalDescription:async()=>{},setRemoteDescription:async()=>{dc.onopen?.({} as Event);},close:()=>{},connectionState:"connected"} as unknown as RTCPeerConnection;
 const deps:VoiceDependencies={secret:async()=>({value:"ephemeral-fixture",expires_at:Date.now()/1000+60}),microphone:async()=>stream,peer:()=>pc,audio:()=>audio,exchange:async()=>"answer"};
 const failed=new RealtimeVoice({...deps,microphone:async()=>{throw new DOMException("denied","NotAllowedError");}});
 await failed.start();check(failed.getSnapshot().phase==="ERROR"&&!failed.getSnapshot().active,"Permission denial leaves microphone off and a readable error");
 const session=new RealtimeVoice(deps);let release:((answer:VoiceAnswer)=>void)|undefined;
 const metadata:Partial<VoiceMessageMetadata>[]=[];const history:string[]=["typed question","typed answer"];
 session.configure({answer:async(text)=>{history.push(text);if(text==="slow")return new Promise(resolve=>{release=resolve;});history.push("answer");return {spokenResponse:"Review the scoped pilot.",visualResponse:"Detailed evidence. ".repeat(100),proposedActions:[],requiresConfirmation:true,conversationState:"awaiting_input",messageId:"reply"};},update:(_,value)=>metadata.push(value),navigate:()=>{throw Error("No navigation expected");}});
 await session.start();check(session.getSnapshot().phase==="LISTENING","Activation listens only after connection");
 const speak=(id:string,text:string)=>{session.handleEvent({type:"input_audio_buffer.speech_started",item_id:id});session.handleEvent({type:"input_audio_buffer.committed",item_id:id});session.handleEvent({type:"input_audio_buffer.speech_stopped",item_id:id});session.handleEvent({type:"conversation.item.input_audio_transcription.completed",item_id:id,transcript:text});};
 speak("a","What needs me?");await wait();
 const response=[...sent].reverse().find(e=>e.type==="response.create");
 check(response?.response.input[0].content[0].text.includes("Review the scoped pilot.")&&!response?.response.input[0].content[0].text.includes("Detailed evidence"),"Only the spoken abstraction reaches audio generation");
 check(response?.response.conversation==="none","Realtime does not own a parallel conversation");
 session.handleEvent({type:"response.created",response:{id:"r1",metadata:response!.response.metadata}});
 session.handleEvent({type:"output_audio_buffer.started",response_id:"r1"});check(session.getSnapshot().phase==="SPEAKING","Speaking begins on output playback event");
 session.handleEvent({type:"response.output_audio_transcript.delta",response_id:"r1",delta:"Review the scoped pilot."});
 session.handleEvent({type:"response.done",response:{id:"r1",status:"completed"}});check(session.getSnapshot().phase==="SPEAKING","Generation ending does not prematurely end playback state");
 session.handleEvent({type:"input_audio_buffer.speech_started",item_id:"b"});check(paused>0&&audio.muted&&session.getSnapshot().phase==="LISTENING","Barge-in silences playback immediately");
 check(sent.some(e=>e.type==="response.cancel")&&sent.some(e=>e.type==="output_audio_buffer.clear"),"Barge-in cancels generation and queued audio");
 check(metadata.some(m=>m.playback==="interrupted"&&m.audioTranscript==="Review the scoped pilot."),"Interrupted audio transcript persists distinctly");
 const before=sent.filter(e=>e.type==="response.create").length;
 speak("slow","slow");await wait();session.interrupt();release!({spokenResponse:"Stale",visualResponse:"Stale detail",proposedActions:[],requiresConfirmation:false,conversationState:"awaiting_input",messageId:"stale"});await wait();
 check(sent.filter(e=>e.type==="response.create").length===before,"Interrupted reasoning cannot emit stale audio");
 session.stop();check(stopped===1&&!session.getSnapshot().active,"Exit stops all microphone tracks");
 history.push("typed follow-up");check(history[0]==="typed question"&&history.includes("What needs me?")&&history[history.length-1]==="typed follow-up","Typed and spoken turns share ordered history");
 check(voiceDepthFor("Brief me on Olympus")==="BRIEF"&&voiceDepthFor("Walk me through the architecture")==="DEEP_DIVE","Response depth follows explicit conversational intent");
 const late=new RealtimeVoice({...deps,microphone:()=>new Promise(resolve=>setTimeout(()=>resolve(stream),5))});const starting=late.start();await wait();late.stop();await starting;check(stopped===2,"Late microphone permission cannot revive a stopped session");
 const known=[{id:"olympus"}];
 check(validateVoiceNavigation({type:"show_projects",status:"NEEDS_YOU"},known)?.type==="show_projects","Structured project attention query can filter the board");
 check(validateVoiceNavigation({type:"open_project",projectId:"olympus"},known)?.type==="open_project","Known project selection is allowed");
 check(validateVoiceNavigation({type:"execute",projectId:"olympus"},known)===null&&validateVoiceNavigation({type:"open_project",projectId:"missing"},known)===null,"Execution and fabricated project navigation are rejected");
 const turn=conversationTurnContent({id:"spoken",role:"assistant",content:"Visual detail",timestamp:"12:00",voice:{kind:"output",spokenResponse:"The concise answer",playback:"interrupted",audioTranscript:"The concise"}});
 check(turn.includes("Visual detail")&&turn.includes("The concise answer")&&turn.includes("interrupted"),"Subsequent typed turns retain visual and spoken context with interruption status");
 const dropped=new RealtimeVoice(deps);await dropped.start();Object.defineProperty(pc,"connectionState",{value:"failed",configurable:true});pc.onconnectionstatechange?.({} as Event);check(dropped.getSnapshot().phase==="ERROR"&&!dropped.getSnapshot().active,"Connection loss stops capture and leaves a readable error");
 Object.defineProperty(pc,"connectionState",{value:"connected",configurable:true});
 const playbackFailure=new RealtimeVoice(deps);await playbackFailure.start();audio.onerror?.({} as Event);check(playbackFailure.getSnapshot().phase==="ERROR"&&!playbackFailure.getSnapshot().active,"Playback failure releases microphone and preserves text fallback");
 failed.stop();late.stop();session.stop();dropped.stop();playbackFailure.stop();return {passed};
}
