export async function runSituationViewportChecks(){
 const checks:string[]=[];const wait=(ms=150)=>new Promise(r=>setTimeout(r,ms));const check=(v:unknown,label:string)=>{if(!v)throw Error(label);checks.push(label)};
 const button=(label:string)=>[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.getAttribute('aria-label')===label||b.textContent===label)!;
 const rect=(selector:string)=>document.querySelector(selector)!.getBoundingClientRect();
 const result=(value:string)=>{document.querySelector('#result')!.textContent=value;window.parent.postMessage({kind:'olympus-viewport-result',result:value},location.origin)};
 try{await wait(650);const page=document.querySelector<HTMLElement>('.center-stack')!,canvas=document.querySelector<HTMLElement>('.relationship-viewport')!,stage=document.querySelector<HTMLElement>('.relationship-stage')!;
 check(page.scrollTop===0,'Initial page scroll is zero');check(rect('.comms-header').height<=80,'Communications header at most 80px');check(document.querySelectorAll('.graph-workstream-card').length===7,'All seven workstreams present');
 check([...document.querySelectorAll<HTMLElement>('.graph-workstream-card')].every(n=>n.scrollHeight<=n.clientHeight+1),'Summary text fits compact nodes');
 const fits=innerWidth>=1500&&innerHeight>=800;
 if(fits){const c=rect('.relationship-viewport'),p=rect('.center-stack');check(c.top>=p.top&&c.bottom<=p.bottom,'Complete canvas initially inside usable viewport');check([...document.querySelectorAll('.graph-node')].every(n=>{const r=n.getBoundingClientRect();return r.left>=c.left-1&&r.right<=c.right+1&&r.top>=c.top-1&&r.bottom<=c.bottom+1}),'All node bounds initially visible');check(rect('.contextual-inspector').bottom<=p.bottom+1,'Inspector bounded above safe area');check(rect('.situation-navigator').top<=rect('.selected-situation-heading').top+1,'Navigator starts with local title');}
 else{check(rect('.relationship-stage').height>=350,'Short window preserves readable detail size');}
 check(![...document.querySelectorAll('.graph-node,.relationship-graph-controls,.contextual-inspector')].some(n=>{const r=n.getBoundingClientRect(),chat=rect('.right-stack');return r.left<chat.right&&r.right>chat.left&&r.top<chat.bottom&&r.bottom>chat.top})||!fits,'Graph, controls and inspector stay clear of chat');check(document.documentElement.scrollWidth<=innerWidth,'No horizontal page overflow');check(canvas.scrollHeight<=canvas.clientHeight+1&&canvas.scrollWidth<=canvas.clientWidth+1,'Default map has no internal scrolling');
 check(!button('Pause lights')&&!button('Enlarge map'),'Old toolbar buttons removed');check(button('Zoom out').disabled,'Minimum zoom disabled');check(stage.dataset.zoomLevel==='0','Opens at default zoom');button('Zoom out').click();await wait();check(stage.dataset.zoomLevel==='0','Cannot go below default zoom');
 const initialTitle=document.querySelector('.selected-situation-heading')!.textContent;
 for(let i=1;i<=4;i++){button('Zoom in').click();await wait();check(stage.dataset.zoomLevel===String(i),'Zoom advances one level to '+i)}
 check(button('Zoom in').disabled,'Maximum zoom disabled');button('Zoom in').click();await wait();check(stage.dataset.zoomLevel==='4','Cannot exceed maximum');check(document.querySelector('.selected-situation-heading')!.textContent===initialTitle,'Zoom preserves situation selection');
 for(let i=3;i>=0;i--){button('Zoom out').click();await wait();check(stage.dataset.zoomLevel===String(i),'Zoom retreats one level to '+i)}
 button('Zoom in').click();await wait();canvas.scrollLeft=40;canvas.scrollTop=30;button('Reset view').click();await wait();check(stage.dataset.zoomLevel==='0'&&canvas.scrollLeft===0&&canvas.scrollTop===0,'Reset restores default zoom and pan');
 button('Zoom in').click();await wait();button('Inspections & repairs').click();await wait();check(document.querySelector<HTMLElement>('.relationship-stage')!.dataset.zoomLevel==='0','Workstream opens at its default framing');
 button('Zoom in').click();await wait();button('Reset view').click();await wait();check(document.querySelector('.workstream-tabs button[aria-pressed=true]')!.textContent==='Inspections & repairs','Reset does not navigate to parent');const actor=document.querySelector<HTMLButtonElement>('.graph-actor button');if(actor){actor.click();await wait();const inspector=document.querySelector('[aria-label="Selected actor inspector"]')!.textContent;button('Zoom in').click();await wait();button('Reset view').click();await wait();check(actor.getAttribute('aria-pressed')==='true','Reset preserves selected actor');check(document.querySelector('[aria-label="Selected actor inspector"]')!.textContent===inspector,'Reset preserves inspector contents')}button('Whole situation').click();await wait();
 const keyboardCanvas=document.querySelector<HTMLElement>('.relationship-viewport')!;keyboardCanvas.dispatchEvent(new KeyboardEvent('keydown',{key:'+',bubbles:true}));await wait();check(document.querySelector<HTMLElement>('.relationship-stage')!.dataset.zoomLevel==='1','Canvas plus shortcut advances one step');keyboardCanvas.dispatchEvent(new KeyboardEvent('keydown',{key:'-',bubbles:true}));await wait();check(document.querySelector<HTMLElement>('.relationship-stage')!.dataset.zoomLevel==='0','Canvas minus shortcut retreats one step');check(![...document.querySelectorAll('.graph-node')].some(n=>{const r=n.getBoundingClientRect(),control=rect('.relationship-graph-controls');return r.left<control.right&&r.right>control.left&&r.top<control.bottom&&r.bottom>control.top}),'Floating controls do not cover nodes at default');
 if(location.search.includes('errors')){const expand=button('Read full context');check(!!expand,'Long briefing offers full context');check(!document.querySelector('.briefing-preview'),'Briefing does not use CSS ellipsis');expand.click();await wait();check(expand.getAttribute('aria-expanded')==='true','Full qualifications expand without rewriting');expand.click();await wait();check(!!document.querySelector('.situation-diagnostic summary [role=alert]'),'Failure impact remains visible');check(!document.querySelector('details.situation-diagnostic[open]'),'Full failure diagnostic initially collapsed');check(document.querySelector('.situation-diagnostic')!.textContent!.includes('No alternate provider'),'Full diagnostic retained');}
 if(location.search.includes('reduced'))check(!document.querySelector('animateMotion'),'Reduced motion disables travel lights');
 button('Zoom in').click();await wait();button('Whole situation').click();await wait();check(document.querySelector<HTMLElement>('.relationship-stage')!.dataset.zoomLevel==='0','Reselecting Whole situation restores overview fit');
 check(getComputedStyle(document.querySelector('.relationship-web')!).transitionDuration==='0s','Zoom framing changes without motion');
 result(`PASS ${checks.length} · ${innerWidth}×${innerHeight}`);
 }catch(e){result(`FAIL ${String(e)} · ${innerWidth}×${innerHeight}\n${checks.join('\n')}`)}
}
