import {documentSituationFixture} from './documentSituationFixture';
import type {SituationSnapshot,SituationContext} from './situations';
export function applyNavigatorFixture(state:SituationSnapshot){
 const context=structuredClone(documentSituationFixture);
 const r=[{sourceId:'agreement',locator:'Synthetic role record'}];
 const actor=(id:string,name:string,kind:'person'|'organization',role:string,status='documented relationship'):SituationContext['entities'][number]=>({id,name,kind,role,status,workstream:'w4',notes:'Synthetic evidence establishes this role. Repair completion is not recorded.',contacts:[],refs:r});
 context.entities.push(actor('inspector','Jordan Vale','person','General Inspector'),actor('inspection','Northstar Inspections','organization','General inspection'),actor('sewer','Canyon Plumbing','organization','Sewer inspector / repair estimate'),actor('roof-person','Robin Taylor','person','Roofing contact'),actor('uncertain-person','Avery Ellis','person','Pest follow-up contact','unconfirmed association'),actor('pest','Example Pest Services','organization','Termite inspection'));
 context.relationships.push({from:'inspector',to:'inspection',description:'Jordan represents Northstar Inspections.',refs:r},{from:'uncertain-person',to:'pest',description:'Avery may represent Example Pest Services.',refs:r});
 for(let i=0;i<12;i++)context.entities.push(actor(`trade-${i}`,i===0?'An unusually long independent architectural inspection organization name':`Example trade ${i+1}`,'organization',i===0?'Detailed investigation and proposed follow-up repairs for previously documented electrical installation issues':'Electrical repair estimate'));
 for(const [workstream,name,role] of [['w2','HomeServices Insurance','Home insurance contact'],['w3','Sample Community Association','Community administration'],['w5','Sample Water Utility','Water service'],['w6','Example Title Office','Closing coordination']])context.entities.push({...actor(workstream+'-org',name,'organization',role),workstream});
 context.entities.push({...actor('mortgage-company','Example Financial','organization','Mortgage services'),workstream:'w1'},{...actor('mortgage-broker','Jamie Morgan','person','Mortgage Broker'),workstream:'w1',contacts:['jamie@example.invalid']},{...actor('mortgage-processor','Taylor Quinn','person','Loan Processor'),workstream:'w1',contacts:['taylor@example.invalid']});
 context.relationships.push({from:'mortgage-broker',to:'mortgage-company',description:'Jamie represents Example Financial.',refs:r},{from:'mortgage-processor',to:'mortgage-company',description:'Taylor represents Example Financial.',refs:r});
 context.entities.push({...actor('pest-long','Northwest Exterminating','organization','Pest service'),workstream:'w6'});
 context.facts.push({label:'Current servicer and payment portal',text:'The current servicer and payment portal have not been confirmed by a servicing statement.',status:'needs confirmation',workstream:'w1',refs:r},{label:'Inspection repairs completed',text:'The inspection report does not establish which recommended repairs were completed.',status:'needs confirmation',workstream:'w4',refs:r},{label:'Signed engagement',text:'The synthetic agreement records the engagement, not payment or work completion.',status:'documented',workstream:'w0',refs:r},{label:'Operator priority',text:'The operator wants to review outstanding work before scheduling new work.',status:'operator context',workstream:'w0',refs:[{sourceId:'update',locator:'Synthetic update'}]});
 state.situations[0]={...state.situations[0],title:'Home',state:'active',localContext:context};
 state.situations[1]={...state.situations[1],title:'Sparse situation',localContext:{...structuredClone(documentSituationFixture),entities:[],relationships:[]}};
 for(let i=2;i<52;i++)state.situations.push({id:`fixture-${i}`,title:`Synthetic situation ${i+1}`,state:i%3?'active':'emerging',stale:false,updatedAt:'2026-09-13T12:00:00Z',briefing:{whereThingsStand:'Synthetic navigation case.'}});
 state.situations[2]={...state.situations[2],title:'Single actor situation',localContext:{...structuredClone(documentSituationFixture),workstreams:[context.workstreams[4]],entities:[actor('single-sewer','Sample Drain Inspection','organization','Sewer inspector')],relationships:[],facts:[]}};
}
