import {createRoot} from "react-dom/client";
import {GmailSettings,type GmailClient} from "./components/panels/GmailSettings";
import {gmailStateLabel,type GmailStatus} from "./services/gmail";
import "./styles.css";
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
let disconnected=0,removed=0,fail=false;
const state:GmailStatus={configured:true,configPath:"C:/Synthetic/gmail-oauth-client.json",busy:false,cachedMessages:1,lastRun:null,candidates:[],account:null};
const api:GmailClient={native:()=>true,status:async()=>structuredClone(state),action:async action=>{if(action==="connect"){state.account={id:"fixture",email:"operator@example.invalid",enabled:true,status:"connected",horizonDays:90,lastAttempt:null,lastSuccess:new Date().toISOString(),lastError:null,nextSync:null};state.lastRun={status:"succeeded",mode:"bounded_full",changes:1,error:null}}if(action==="disconnect"){disconnected++;state.account!.enabled=false;state.account!.status="disconnected"}if(action==="sync"&&fail)throw "gmail_network_unavailable";},horizon:async days=>{state.account!.horizonDays=days},search:async()=>[{provider:"gmail",accountId:"fixture",messageId:"ab",threadId:"aa",sender:"Brandon <brandon@example.invalid>",subject:"Atlas closing documents",timestamp:Date.now(),excerpt:"Can you review? <script>bad()</script>",fingerprint:"synthetic-fingerprint",retrievedAt:new Date().toISOString(),bodyStatus:"text_available",cachedThreadSubset:true}],thread:async()=>[{id:"ab",threadId:"aa",sender:"brandon@example.invalid",recipients:"operator@example.invalid",subject:"Atlas closing documents",internalDate:Date.now(),canonicalText:"Can you review? <script>bad()</script>",cleanText:"Can you review?",bodyStatus:"text_available",attachments:[]}],removeCache:async()=>{removed++;state.cachedMessages=0}};
createRoot(document.getElementById("root")!).render(<main style={{padding:24,maxWidth:650,margin:"auto"}}><h2>Gmail connection</h2><p>Synthetic UI acceptance fixture. No Gmail access or real credentials.</p><GmailSettings api={api}/><pre id="result" style={{whiteSpace:"pre-wrap"}}/></main>);
async function run(){const checks:string[]=[];const assert=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label)};const button=(label:string)=>[...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===label)!;
 try{await wait(250);document.querySelector('details')!.open=true;assert(document.body.textContent?.includes("Not connected"),"Disconnected state hydrates");button("Connect Gmail").click();await wait(150);assert(document.body.textContent?.includes("operator@example.invalid"),"Connected identity hydrates");assert(document.body.textContent?.includes("read only"),"Read-only status is visible");assert(document.body.textContent?.includes("bounded full"),"Sync receipt is visible");assert(document.body.textContent?.includes("sent to your reasoning provider"),"Model-use disclosure is visible");assert(document.body.textContent?.includes("Background situation understanding"),"Background analysis disclosure remains visible");assert(document.body.textContent?.includes("Olympus cannot send or change mail"),"No-write boundary disclosed");
 const input=document.querySelector('input')!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,"closing");input.dispatchEvent(new Event('input',{bubbles:true}));await wait(50);document.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await wait(120);assert(document.body.textContent?.includes("Atlas closing documents"),"Search result renders");document.querySelector<HTMLButtonElement>('.gmail-result')!.click();await wait(100);assert(document.body.textContent?.includes("Gmail ab"),"Thread retains provider ID");assert(!document.querySelector('.gmail-thread-message script'),"Mail HTML remains inert text");
 fail=true;button("Sync now").click();await wait(100);assert(document.querySelector('[role="alert"]')?.textContent?.includes("Network unavailable"),"Offline error preserves connection");fail=false;
 button("Disconnect").click();await wait(100);assert(disconnected===1&&state.cachedMessages===1,"Disconnect retains cached mail");assert(!document.querySelector('.gmail-result'),"Disconnect hides retrieved mail");button("Remove cached mailbox").click();await wait(60);assert(removed===0,"Cache removal requires explicit confirmation");button("Keep cache").click();await wait(60);assert(removed===0,"Declining cache removal is safe");button("Remove cached mailbox").click();await wait(60);button("Confirm cache removal").click();await wait(100);assert(removed===1&&state.cachedMessages===0,"Confirmed removal is separate from disconnect");
 state.account!.enabled=true;state.account!.status="authentication_required";assert(gmailStateLabel(state)==="Authentication required","Expired authorization is distinct from disconnection");state.busy=true;state.account!.status="syncing";assert(gmailStateLabel(state)==="Synchronizing…","Sync progress has an explicit state");assert(document.documentElement.scrollWidth<=innerWidth,"Panel fits viewport");document.getElementById('result')!.textContent=`PASS (${checks.length})\n`+checks.join('\n');
 }catch(e){document.getElementById('result')!.textContent='FAIL '+String(e)+'\n'+checks.join('\n')}
}
if(location.search.includes("run"))void run();
