import {createRoot} from "react-dom/client";
import {useState} from "react";
import {mockIPC} from "@tauri-apps/api/mocks";
import {CommandInstrument} from "./components/panels/CommandInstrument";
import {HybridCoreSetting} from "./components/panels/HybridCommandCore";
import {commandLayout,nodeDepth,setHybridEnabled} from "./services/hybridCore";
import {runProjectConstellationHarness} from "./services/projectConstellation.harness";
import {EMPTY_VAULT_GRAPH,type VaultGraphPayload} from "./services/vaultGraph";
import type {TrackedProject} from "./types";
import type {OlympusVisualState} from "./services/ambientMotion";
import "./styles.css";
let reduced=false, visibility="visible";
const motionListeners=new Set<()=>void>();
const nativeMatchMedia=window.matchMedia.bind(window);
window.matchMedia=((query:string)=>query==='(prefers-reduced-motion: reduce)'?{get matches(){return reduced},addEventListener:(_:string,fn:()=>void)=>motionListeners.add(fn),removeEventListener:(_:string,fn:()=>void)=>motionListeners.delete(fn)}:nativeMatchMedia(query)) as typeof window.matchMedia;
Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>visibility});
const names=["Olympus","Pokedex","Agentic AI","AI Learning","Fidelity","Obsidian","Health App","Fruit Organizer"];
const projects:TrackedProject[]=names.map((name,i)=>({id:`p${i}`,name,path:`C:/fixture/${i}`,status:i<2?"active":"watching",statusSource:"declared",promoted:null,branch:"main",lastCommit:"fixture",lastCommitAt:null,repoState:"git-active",recentCommits:[],sinceSessionCommits:[],linkedWorktrees:[],summary:"",vision:"",visionReviewedAt:null,nextStep:"",notePath:`project-${i}.md`,warnings:[]}));
const graph:VaultGraphPayload={...EMPTY_VAULT_GRAPH,nodes:projects.map(p=>({id:p.notePath!,title:p.name,folder:"Projects",isProject:true,degree:1,hop:0})),edges:[]};
for(let i=0;i<64;i++){const id=`note-${String(i).padStart(3,"0")}.md`;graph.nodes.push({id,title:id,folder:`Folder ${i%4}`,isProject:false,degree:2,hop:1});graph.edges.push({from:projects[i%8].notePath!,to:id});}
mockIPC(command=>{if(command==="fetch_vault_graph")return graph;if(command==="fetch_recent_vault_writes")return [];if(command==="fetch_operator_profile")return null;throw Error(`Unexpected fixture command: ${command}`);});
setHybridEnabled(!location.search.includes("run"));
function Fixture(){const [state,setState]=useState<OlympusVisualState>("idle");const [action,setAction]=useState("Fixture data · no project writes");return <><aside style={{position:"fixed",left:24,top:24,width:220,zIndex:5}}><h2>DIMENSIONAL CORE</h2><HybridCoreSetting/><label>System state <select value={state} onChange={e=>setState(e.target.value as OlympusVisualState)}>{["idle","listening","thinking","speaking","executing","complete","error"].map(s=><option key={s}>{s}</option>)}</select></label><p>{action}</p><pre id="result" style={{whiteSpace:"pre-wrap",fontSize:11}}>Visual preview</pre></aside><main style={{height:"100vh",paddingLeft:200}}><CommandInstrument projects={projects} tasks={[]} tasksLoading={false} tasksError={null} visualState={state} voiceLevel={state==="speaking"?.65:0} onSelectProject={id=>setAction(`Selected ${id}`)} onOpenNote={id=>setAction(`Opened ${id}`)}/></main></>}
createRoot(document.getElementById("root")!).render(<Fixture/>);
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function run(){const checks:string[]=[];const assert=(ok:unknown,msg:string)=>{if(!ok)throw Error(msg);checks.push(msg);document.getElementById("result")!.textContent=checks.join("\n")};const ready=async()=>{for(let i=0;i<100;i++){if(document.querySelector('[data-renderer="hybrid"]'))return;await wait(100);}throw Error("3D did not initialize");};
try{await wait(600);const original=[...document.querySelectorAll('.project-ring__hit')].map(e=>e.getAttribute('d'));assert(runProjectConstellationHarness().passed,"Existing constellation invariants");const layout=commandLayout(projects,graph,1);assert(layout.constellation.nodes.every(n=>Number.isFinite(nodeDepth(n.id))&&Math.abs(nodeDepth(n.id))<=12),"Bounded deterministic node depth");setHybridEnabled(true);await ready();await wait(600);assert(JSON.stringify(original)===JSON.stringify([...document.querySelectorAll('.project-ring__hit')].map(e=>e.getAttribute('d'))),"Project hit geometry unchanged");assert(document.querySelectorAll('.hybrid-core canvas').length===1,"One WebGL canvas");const canvas=document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!;assert(canvas.dataset.nodes==='64',"All 64 real fixture nodes retained");assert(['2','3'].includes(canvas.dataset.rings!),"Two base rings; at most one additional");document.querySelector<SVGElement>('.project-ring__hit')!.dispatchEvent(new MouseEvent('click',{bubbles:true}));await wait(100);assert(document.body.textContent?.includes('Selected p'),"Existing project action preserved");canvas.getContext('webgl2')!.getExtension('WEBGL_lose_context')!.loseContext();await wait(400);assert(document.querySelector('[data-renderer="svg"]')&&document.body.textContent?.includes('Graphics context lost'),"Context loss restores original SVG");setHybridEnabled(false);await wait(100);assert(!document.querySelector('.hybrid-core canvas'),"Canvas removed on disable");setHybridEnabled(true);await ready();assert(document.querySelectorAll('.hybrid-core canvas').length===1,"Re-enable recreates one healthy scene");reduced=true;motionListeners.forEach(fn=>fn());await wait(850);let frozen=document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!.dataset.frames;await wait(800);assert(document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!.dataset.frames===frozen,'Reduced motion stops GPU animation');reduced=false;motionListeners.forEach(fn=>fn());await wait(700);assert(document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!.dataset.frames!==frozen,'Motion resumes');visibility='hidden';document.dispatchEvent(new Event('visibilitychange'));await wait(850);frozen=document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!.dataset.frames;await wait(800);assert(document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!.dataset.frames===frozen,'Hidden view stops GPU rendering');visibility='visible';document.dispatchEvent(new Event('visibilitychange'));await wait(700);assert(document.querySelector<HTMLCanvasElement>('.hybrid-core canvas')!.dataset.frames!==frozen,'Visible view resumes');
setHybridEnabled(false);await wait(200);const originalContext=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(this:HTMLCanvasElement,...args:any[]){return args[0]==='webgl2'?null:(originalContext as any).apply(this,args)} as any;setHybridEnabled(true);await wait(500);assert(document.querySelector('[data-renderer="svg"]')&&document.body.textContent?.includes('WebGL 2 is unavailable'),'Missing WebGL restores SVG');HTMLCanvasElement.prototype.getContext=originalContext;setHybridEnabled(false);await wait(200);setHybridEnabled(true);await ready();
document.getElementById('result')!.textContent='PASS\n'+checks.join('\n');}catch(e){document.getElementById('result')!.textContent='FAIL '+String(e)+'\n'+checks.join('\n');}}
if(location.search.includes('run'))void run();
