import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {RelationshipDossier} from './components/panels/RelationshipDossier';
import {dossierFixture} from './services/relationshipDossierFixture';
import {projectContextualActors} from './services/contextualActors';
import './styles.css';
import './components/panels/situations.css';
const fixtureOpens:string[]=[];
const documentsApi={status:async()=>context.sources.map(s=>({id:s.id,available:s.id!=='design',openable:s.id!=='design'})),open:async(_situationId:string,sourceId:string)=>{fixtureOpens.push(sourceId)}};
const context=dossierFixture(),actors=projectContextualActors('synthetic',context);
function Harness(){const [id,setId]=useState(actors.find(a=>a.primary==='Example Renovations')!.id);const actor=actors.find(a=>a.id===id);return <main className="dossier-study" style={{maxWidth:1050,margin:'24px auto',padding:16}}><h2>Relationship dossier study</h2><p>Synthetic contacts and records only. No mail or model calls.</p><nav aria-label="Dossier examples" style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:16}}>{actors.map(a=><button key={a.id} onClick={()=>setId(a.id)}>{a.primary}</button>)}</nav><article className="situation-briefing contextual-inspector" style={{width:'min(480px,100%)',height:760,maxHeight:'80vh',overflow:'auto',background:'#0c1823',padding:18}}>{actor?<RelationshipDossier key={id} context={context} actor={actor} situationId="synthetic" documentsApi={documentsApi} onBack={()=>setId('')}/>:<p>Parent workstream briefing</p>}</article><pre id="result"/></main>}
createRoot(document.getElementById('root')!).render(<Harness/>);
const wait=()=>new Promise(r=>setTimeout(r,100));
async function run(){await wait();let count=0;const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);count++};const click=(name:string)=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent===name);if(!b)throw Error(name);b.click()};
 for(const actor of actors){click(actor.primary);await wait();const panel=document.querySelector('.relationship-dossier')!;check(panel.querySelector('h4')?.textContent===actor.primary,'identity');check(panel.querySelectorAll('[role=tab]').length>=3,'detail tabs');check(panel.querySelector('[role=tab][aria-selected=true]')?.textContent==='Overview','overview default');check(!panel.textContent?.includes('ACTOR IN THIS SITUATION'),'old label absent');}
 click('Example Renovations');await wait();check(document.querySelector('.dossier-contacts')?.textContent?.includes('(202) 555-0148'),'full contacts');check(document.querySelector('.dossier-contacts')?.textContent?.includes('example.invalid'),'synthetic email');check(document.querySelector('.relationship-dossier')?.textContent?.includes('not evidence of payment'),'agreed versus paid');check(document.querySelector('.relationship-dossier')?.textContent?.includes('remains an estimate'),'planned versus completed');
 click('Documents');await wait();check(document.querySelectorAll('.dossier-document').length===5,'scoped document set');check(document.querySelector('[role=tabpanel]')?.textContent?.includes('Created by operator'),'ownership retained');check(document.querySelector('[role=tabpanel]')?.textContent?.includes('Received document'),'received source');check(document.querySelector('[role=tabpanel]')?.textContent?.includes('file not currently available'),'missing file honest');check(!document.querySelector('[aria-label="Open document: Kitchen 3D renderings"]'),'no open missing file');document.querySelector<HTMLButtonElement>('[aria-label="Open document: Flooring quote"]')!.click();await wait();check(fixtureOpens.includes('quote'),'open uses source ID');
 click('Related');await wait();check(document.querySelector('[role=tabpanel]')?.textContent?.includes('Casey Rivers'),'related canonical representative');check(document.querySelector('[role=tabpanel]')?.textContent?.includes('Unconfirmed'),'uncertain suppliers retained');
 click('Timeline');await wait();check(document.querySelectorAll('.dossier-timeline li').length===5,'meaningful milestones');check(document.querySelector('[data-event-state=planned]')?.textContent==='planned','planned remains planned');check(document.querySelectorAll('[data-event-state=reported]').length===3,'reported remains reported');check(!document.querySelector('[role=tabpanel]')?.textContent?.includes('sync'),'no execution log');
 click('← Renovation');await wait();check(!document.querySelector('.relationship-dossier'),'back clears actor');check(document.querySelector('.contextual-inspector')?.textContent?.includes('Parent workstream briefing'),'back shows parent');click('Robin Taylor');await wait();check(!document.querySelector('.dossier-contacts'),'no empty contacts');check(document.querySelector('.relationship-dossier')?.textContent?.includes('originally established is not recorded'),'unknown origin');check(document.querySelector('.relationship-dossier')?.textContent?.includes('Organization unconfirmed'),'person only');
 click('Northstar Inspections');await wait();check(document.querySelector('.dossier-identity')?.textContent?.includes('Jordan Vale'),'combined company/person');check(document.querySelector('.relationship-dossier')?.textContent?.includes('Earliest documented interaction'),'precise history');
 click('Example Archive Services');await wait();check((document.querySelector('[role=tabpanel]>section:nth-of-type(3)')?.textContent?.length??0)<300,'long history compact');check(![...document.querySelectorAll('[role=tab]')].some(t=>t.textContent==='Timeline'),'no empty timeline tab');click('Documents');await wait();check(document.querySelectorAll('.dossier-document').length>=30,'all history retained');click('Related');await wait();check(document.querySelectorAll('.dossier-related').length===9,'dense related set retained');check(!document.querySelector('button[aria-label="Send"]'),'no sending');
 document.querySelector('#result')!.textContent=`PASS ${count} dossier checks`;click('Example Renovations');}
if(location.search.includes('run'))void run().catch(e=>{document.querySelector('#result')!.textContent='FAIL '+e.message});
