import {createRoot} from 'react-dom/client';
import {SituationsWorkspace} from './components/panels/SituationsWorkspace';
import {fixtureSituations,fixtureState,fixtureDraftCalls} from './services/situationsFixture';
import {BackgroundLayer} from './components/BackgroundLayer';
import './styles.css';
import {applyNavigatorFixture} from './services/situationNavigatorFixture';
if(location.search.includes('navigator'))applyNavigatorFixture(fixtureState);
import {documentSituationFixture} from './services/documentSituationFixture';
if(location.search.includes('documents')){
 fixtureState.situations[0].localContext=documentSituationFixture;
 fixtureState.situations[0].title='Home';
}
if(location.search.includes('reduced')){const original=window.matchMedia.bind(window);window.matchMedia=(query:string)=>query==='(prefers-reduced-motion: reduce)'?{...original(query),matches:true,media:query,addEventListener:()=>{},removeEventListener:()=>{}} as MediaQueryList:original(query)}
let opened='';
createRoot(document.getElementById('root')!).render(<><BackgroundLayer/><main style={{position:'relative',maxWidth:1250,margin:'30px auto',padding:28,background:'#07111bef',border:'1px solid #304351',borderRadius:16}}><h1 className="olympus-wordmark">OLYMPUS</h1><p>SITUATION INTELLIGENCE · SYNTHETIC DESIGN STUDY</p><small>No real mail, accounts or model calls. Home-purchase content is illustrative.</small><SituationsWorkspace api={fixtureSituations} onOpen={row=>{opened=row.threadId}}/><pre id="result"/></main></>);
const wait=(ms=150)=>new Promise(r=>setTimeout(r,ms));
async function run(){const checks:string[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};const button=(text:string)=>[...document.querySelectorAll('button')].find(b=>b.textContent===text)!;const set=(selector:string,value:string)=>{const e=document.querySelector(selector) as HTMLInputElement|HTMLTextAreaElement;Object.getOwnPropertyDescriptor(e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(e,value);e.dispatchEvent(new Event('input',{bubbles:true}))};await wait(400);
 check(fixtureDraftCalls===0,'No automatic drafting');check(document.querySelectorAll('.situation-person').length===4,'Relationship map deduplicates people');
 (document.querySelector('[aria-label="View Morgan Ellis"]') as SVGGElement).dispatchEvent(new MouseEvent('click',{bubbles:true}));await wait();check(document.querySelectorAll('.situation-log').length===1,'Person selection filters conversation log');button('Open conversation').click();check(opened==='aa','Source inspection uses the actual thread');
 button('Draft reply').click();await wait();check(fixtureDraftCalls===1,'Drafting is on demand');set('[aria-label="Draft message"]','My unsaved edit');await wait();const node=document.querySelector('[aria-label="View Morgan Ellis"]');const label=node?.textContent;fixtureState.observations[1].people.push({email:'pat@example.invalid',name:'Pat',role:'Contractor'});await wait(3200);check((document.querySelector('[aria-label="Draft message"]') as HTMLTextAreaElement).value==='My unsaved edit','Polling preserves unsaved draft text');check(document.querySelector('[aria-label="View Morgan Ellis"]')===node,'Polling retains existing map nodes');check(node?.textContent===label,'New people preserve existing actor identity and role');check(document.querySelectorAll('.situation-log').length===1,'Polling preserves person focus');button('Save local draft').click();await wait();check(fixtureState.drafts[0].body==='My unsaved edit'&&fixtureState.drafts[0].revision===2,'Local draft save advances revision');
 set('[aria-label="Situation update"]','The insurance policy is now purchased.');await wait();(document.querySelector('[aria-label="Situation update"]')!.closest('form')!).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await wait();check(fixtureState.updates.length===1,'Operator update saved');
 button('Overview · 2').click();await wait();check(document.querySelectorAll('.situation-overview>article').length===2,'Overview presents available situations');check((document.querySelector('[aria-label="Draft message"]') as HTMLTextAreaElement).value==='My unsaved edit','Changing views preserves draft');
 check(![...document.querySelectorAll('button')].some(b=>/^send$/i.test(b.textContent??'')),'No send control exists');
 document.getElementById('result')!.textContent=`PASS ${checks.length}\n${checks.join('\n')}`;
}
if(location.search.includes('run')&&!location.search.includes('navigator'))void run().catch(e=>{document.getElementById('result')!.textContent=`FAIL ${e.message}`});

async function navigatorChecks(){const checks:string[]=[];const check=(v:unknown,label:string)=>{if(!v)throw Error(label);checks.push(label)};const click=(label:string)=>{const b=[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent===label||b.getAttribute('aria-label')===label);if(!b)throw Error('Missing '+label);b.click()};try{for(let attempt=0;attempt<100&&!document.querySelector('[aria-label="Ongoing briefing"]');attempt++)await wait(100);

 check(document.querySelectorAll('.briefing-unknowns li').length===3,'Overview shows three discrete recorded questions');check(!document.querySelector('[aria-label="Ongoing briefing"]')?.textContent?.includes('WHAT CHANGED'),'Whole overview keeps changes secondary');check(!!document.querySelector('.briefing-next-step'),'Next step has primary treatment');check(!document.querySelector('details.document-evidence[open]'),'Evidence initially collapsed');const factsDisclosure=[...document.querySelectorAll('details')].find(d=>d.querySelector('summary')?.textContent?.startsWith('Facts & open questions'))!;check(!factsDisclosure.open,'Facts initially collapsed');factsDisclosure.querySelector('summary')!.click();check(factsDisclosure.textContent?.includes('KNOWN · DOCUMENTED')&&factsDisclosure.textContent?.includes('OPEN QUESTIONS')&&factsDisclosure.textContent?.includes('OPERATOR CONTEXT'),'Documented, operator and unresolved records separated');factsDisclosure.querySelector('summary')!.click();click('Utilities');await wait();check(document.querySelector('[aria-label="Ongoing briefing"]')?.textContent?.includes('No open questions recorded for this scope'),'No-unknown scope avoids inventing questions');click('Whole situation');await wait();check(!!document.querySelector('button[aria-label="Refresh now"] svg'),'Refresh remains accessible as compact icon');
 check(document.querySelectorAll('.situation-nav-card').length===52,'52 situations in vertical navigator');check(!document.querySelector('.situations>nav'),'No horizontal situation selector');
 const rail=document.querySelector<HTMLElement>('.situation-nav-scroll')!;check(rail.scrollHeight>rail.clientHeight,'Navigator independently scrollable');rail.scrollTop=240;const offset=rail.scrollTop;
 (document.querySelectorAll<HTMLButtonElement>('.situation-nav-card')[1]).click();await wait();check(rail.scrollTop===offset,'Switching preserves navigator scroll');check(document.querySelectorAll('.contextual-actor').length===0,'Sparse context invents no actors');
 (document.querySelector('.situation-nav-card') as HTMLButtonElement).click();await wait();check(rail.scrollTop===offset,'Returning preserves navigator scroll');click('Inspections & repairs');await wait();
 check(document.querySelector('.selected-situation-heading h3')?.textContent==='Home','Workstream selection stays within Home');
 check(document.querySelectorAll('.contextual-actor').length<=8,'Dense focus is paginated');click('More actors');await wait();
 const combined=document.querySelector<HTMLButtonElement>('[aria-label="View Northstar Inspections"]');check(combined?.textContent?.includes('Jordan Vale'),'Company and representative share one graph node');check(!document.querySelector('[aria-label="View Jordan Vale"]'),'No duplicate representative node');combined!.click();await wait();
 check(document.querySelector('[aria-label="Selected actor inspector"]')?.textContent?.includes('General inspection'),'Actor inspector preserves role');check(document.querySelector('[aria-label="Selected actor inspector"]')?.textContent?.includes('inspector'),'Canonical identities remain inspectable');
 check(!!document.querySelector('.relationship-dossier .dossier-provenance:not([open])')&&document.querySelectorAll('.relationship-dossier [role=tab]').length>=3,'Dossier records start collapsed');click('← Inspections & repairs');await wait();check(!!document.querySelector('[aria-label="Ongoing briefing"]')&&!document.querySelector('.relationship-dossier'),'Parent back restores briefing only');check(document.querySelector('.workstream-tabs button[aria-pressed=true]')?.textContent==='Inspections & repairs','Parent back preserves map scope');combined!.click();await wait();check(document.querySelector('.relationship-dossier h4')?.textContent==='Northstar Inspections','Reselect opens correct dossier');
 check(document.querySelector('[aria-label="View Robin Taylor"]')?.textContent?.includes('Organization unconfirmed'),'Person-only actor preserves uncertainty');check(!!document.querySelector('[aria-label="View Avery Ellis"]')&&!!document.querySelector('[aria-label="View Example Pest Services"]'),'Uncertain affiliation remains separate');click('More actors');await wait();check(!!document.querySelector('[aria-label="View Canyon Plumbing"]'),'Organization-only actor displayed');
 click('Whole situation');await wait();check(document.querySelectorAll('.graph-group').length===7,'Whole view groups seven workstreams');check(document.querySelectorAll('.contextual-actor').length<=7,'Whole view uses progressive disclosure');check(document.querySelectorAll('.graph-edge').length>=7,'Graph renders real structural edges');check(!document.querySelector('.actor-lane'),'Card lanes removed');check(!!document.querySelector('.graph-anchor'),'Situation anchor remains in graph');check(document.querySelectorAll('.graph-workstream-card').length===7,'Overview renders seven rich workstream nodes');check(document.querySelector('.graph-workstream-preview')?.textContent?.includes('Example Renovations'),'Workstream node previews actual actors');check(![...document.querySelectorAll('button')].some(b=>b.textContent==='Pause lights'||b.textContent==='Enlarge map'),'Old map toolbar removed');if(location.search.includes('reduced'))check(!document.querySelector('animateMotion'),'Reduced motion creates no traveling light animations');else check(document.querySelectorAll('animateMotion').length===7,'One light follows each overview connection');
 check(document.documentElement.scrollWidth<=innerWidth,'No horizontal page overflow');check(document.querySelector('[aria-label="Ongoing briefing"]')?.textContent?.includes('USEFUL NEXT STEP'),'Brief retains useful next step');check(fixtureDraftCalls===0,'Navigation invokes no drafting');
 const canvas=document.querySelector<HTMLElement>('.relationship-viewport')!;check(canvas.scrollHeight<=canvas.clientHeight+1&&canvas.scrollWidth<=canvas.clientWidth+1,'Fit map needs no canvas scrolling');
 const nodes=[...document.querySelectorAll('.graph-node')];check(new Set(nodes.map(n=>n.getAttribute('data-node-id'))).size===nodes.length,'Visible graph IDs unique');
 check([...document.querySelectorAll('.graph-actor button')].every(n=>getComputedStyle(n).animationName==='none'),'Graph nodes have no continuous motion');
 click('Zoom in');await wait();check(canvas.scrollWidth>canvas.clientWidth,'Zoom provides readable detail');click('Reset view');await wait();check(canvas.scrollWidth<=canvas.clientWidth+1,'Reset restores bounded canvas');
 for(const workstream of ['Renovation','Mortgage','Insurance','HOA','Inspections & repairs','Utilities','Closing']){click(workstream);await wait();check(document.querySelector('.graph-anchor strong')?.textContent===workstream||document.querySelector('.graph-anchor-content strong')?.textContent===workstream,workstream+' anchor');check(document.querySelectorAll('.graph-actor').length<=8,workstream+' bounded actors');const first=document.querySelector<HTMLButtonElement>('.graph-actor button');if(first){first.click();await wait();check(document.querySelectorAll('.relationship-dossier [role=tab]').length>=3,workstream+' dossier consistent');click('← '+workstream);await wait();check(!!document.querySelector('[aria-label="Ongoing briefing"]'),workstream+' back returns briefing');}}
 click('Mortgage');await wait();check(document.querySelectorAll('[aria-label^="View Example Financial"]').length===2,'Separate broker and processor engagements');check(!document.querySelector('[aria-label="View Jamie Morgan"]')&&!document.querySelector('[aria-label="View Taylor Quinn"]'),'Representatives are not duplicate standalone nodes');click('Whole situation');await wait();check(document.querySelector('[title="HomeServices Insurance"]')?.textContent?.replace(/\s/g,'')==='HomeServicesInsurance','Important insurance name retained');check(document.querySelector('[title="Northwest Exterminating"]')?.textContent?.includes('\n'),'Long provider wraps by words');
 document.getElementById('result')!.textContent=`PASS ${checks.length} navigator checks\n${checks.join('\n')}`;
 }catch(e){document.getElementById('result')!.textContent=`FAIL ${e}\n${checks.join('\n')}`}}
if(location.search.includes('navigator')&&location.search.includes('run'))void navigatorChecks();
