import {createRoot} from "react-dom/client";
import {useState} from "react";
import {ChatPanel} from "./components/panels/ChatPanel";
import type {ConversationMessage} from "./types";
import {runRealtimeVoiceHarness} from "./services/realtimeVoice.harness";
import "./styles.css";
const seed:ConversationMessage[]=[{id:"typed",role:"user",content:"What needs me?",timestamp:"12:00"},{id:"voice",role:"assistant",content:"The project board has no confirmed operator checkpoints. Seven projects have unconfirmed operational state. The details remain here in your shared conversation.",timestamp:"12:01",voice:{kind:"output",spokenResponse:"No operator checkpoints are confirmed. Seven projects still need their operational state recorded.",playback:"interrupted",requiresConfirmation:true}}];
function Fixture(){const [messages,setMessages]=useState(seed);return <><output id="results" style={{position:"fixed",top:20,left:20,color:"white",maxWidth:650}}>Ready</output><div style={{position:"fixed",right:20,bottom:20,width:380,height:"calc(100vh - 60px)",display:"flex",alignItems:"flex-end"}}><ChatPanel messages={messages} onSendMessage={text=>setMessages(current=>[...current,{id:"follow-up",role:"user",content:text,timestamp:"12:02"}])} onRecordObservation={async()=>({tone:"success",message:"Fixture only"})}/></div></>;}
createRoot(document.getElementById("root")!).render(<Fixture/>);
const wait=()=>new Promise(resolve=>setTimeout(resolve,100));
async function run(){const protocol=await runRealtimeVoiceHarness();await wait();const input=document.querySelector<HTMLTextAreaElement>('[aria-label="Command to Olympus"]')!;input.focus();Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value")!.set!.call(input,"Keep my typed follow-up");input.dispatchEvent(new Event("input",{bubbles:true}));await wait();document.querySelector<HTMLButtonElement>('[aria-label="Start voice conversation"]')!.click();await wait();if(input.value!=="Keep my typed follow-up")throw Error("Draft lost on voice failure");if(!document.body.textContent?.includes("desktop app"))throw Error("Missing graceful fallback");document.querySelector<HTMLButtonElement>('[aria-label="Send command"]')!.click();await wait();if(!document.body.textContent?.includes("Keep my typed follow-up"))throw Error("Text disabled after failure");if(!document.body.textContent?.includes("Playback interrupted"))throw Error("Missing interruption disclosure");if(!document.body.textContent?.includes("Authorization required"))throw Error("Missing confirmation boundary");document.getElementById("results")!.textContent=`PASS: ${protocol.passed} simulated protocol checks; draft preserved on voice failure; text send remains available; interruption and authorization visible.`;}
if(location.search.includes("run"))void run().catch(error=>{document.getElementById("results")!.textContent=`FAIL ${String(error)}`;});
